spring:
  data:
    mongodb:
      uri: mongodb+srv://akashbhasme09:Akash%402001@cluster0.lxusx.mongodb.net/?retryWrites=true&w=majority&appName=cluster0
      database: journaldb
      auto-index-creation: true

  redis:
#    uri: redis-cli -u redis://default:9iKXbUlTwFqqtPNCbZjX8acio1WU53jm@redis-17434.c212.ap-south-1-1.ec2.redns.redis-cloud.com:17434
    host: redis-17434.c212.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 17434
    password: 9iKXbUlTwFqqtPNCbZjX8acio1WU53jm

  mail:
    host: smtp.gmail.com
    port: 587
    username: akashbhasme011@gmail.com
    password: wtyi tsms nnjk pwwk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 6060

logging:
  level:
    net:
      engineeringdigest:
        journalApp: DEBUG

weather:
  api:
    key: e307e42b908583469225a554f97adb7f
